py/Django-app/Cinema/Cinema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('ticketing/', include('ticketing.urls')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

py/Django-app/Cinema/ticketing/urls.py
from django.urls import path

from . import views

app_name = 'ticketing_app'
urlpatterns = [
    path('movie/list', views.movie_list, name='movie_list'),
    path('movie/details/<int:movie_id>/', views.movie_details, name='movie_datails'),
    path('cinema/details/<int:cinema_id>', views.cinema_details, name='cinema_details'),
    path('cinema/list', views.cinema_list, name='cinema_list'),
    path('showtime/list', views.showtime_list, name='showtime_list')
]

py/Django-app/Cinema/ticketing/models.py
from django.db import models


class Movie(models.Model):
    """
    define Movie Model
    """

    class Meta:
        verbose_name = "فیلم"
        verbose_name_plural = "فیلم ها"

    name = models.CharField(max_length=100, verbose_name="نام فیلم")
    director = models.CharField(max_length=50, verbose_name="کارگردان فیلم")
    year = models.IntegerField(default=1380, verbose_name="سال ساخت فیلم")
    length = models.IntegerField(default=120, verbose_name="زمان فیلم")
    description = models.TextField("توضیحات", null=True)
    poster = models.ImageField("پوستر", upload_to='imageposter/')

    def __str__(self):
        return self.name


class Cinema(models.Model):
    """
    define Cinema Model
    """

    class Meta:
        verbose_name = "سینما"
        verbose_name_plural = "سینماها"

    cinema_code = models.IntegerField("کد سینما", primary_key=True)
    name = models.CharField("نام سینما", max_length=50)
    city = models.CharField("شهر سینما", max_length=40, default='اصفهان')
    phone = models.IntegerField("شماره تلفن سینما", null=True)
    capacity = models.IntegerField("ظرفیت سینما", default=100)
    address = models.TextField("آدرس سینما", null=True)
    poster = models.ImageField('پوستر', upload_to='imageposter/', null=True, blank=True)

    def __str__(self):
        return self.name


class ShowTime(models.Model):
    """
    define ShowTime Model
    """

    class Meta:
        verbose_name = "سانس"
        verbose_name_plural = "سانس ها"

    movie = models.ForeignKey('Movie', on_delete=models.PROTECT, verbose_name="نام فیلم")
    cinema = models.ForeignKey('Cinema', on_delete=models.PROTECT, verbose_name="نام سینما")
    start_time = models.DateTimeField("زمان سانس")
    price = models.IntegerField("قیمت")
    sabale_seats = models.IntegerField('تعداد صندلی ها')
    free_seats = models.IntegerField("تعداد صندلی خالی")
    SALE_NOT_STARTED = 1
    SALE_OPEN = 2
    TICKETS_SALE = 3
    SALE_CLOSED = 4
    MOVIE_PLAYED = 5
    SHOW_CANSELED = 6
    status_choice = (
        (SALE_NOT_STARTED, "فروش آغاز نشده"),
        (SALE_OPEN, "در حال فروش بلیط"),
        (TICKETS_SALE, "بلیط ها تمام شد"),
        (SALE_CLOSED, "فروش بلیط بسته شد"),
        (MOVIE_PLAYED, "فیلم پخش شد"),
        (SHOW_CANSELED, "سانس لغو شد"),
    )
    # status for showtime of film
    status = models.IntegerField("وضعیت", choices=status_choice)

    def __str__(self):
        return '{} - {} - {}'.format(self.movie, self.cinema, self.start_time)

    def get_price_display(self):
        return "{} تومان".format(self.price)

    def get_status_display(self):
        return self.status_choice[self.status-1][1]

    # this is a query of show time model -------->      ShowTimw.objects.filter(movie__year__gt=1380,
    # cinema__city="Tehran").exclude(price__lt=1000)

py/Django-app/Cinema/ticketing/views.py
from cgitb import html
from html.entities import html5
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from ticketing.models import Movie, Cinema, ShowTime


# view of url movie/list with name movie_list
def movie_list(request):
    # query for return all objects in Movie model
    movies = Movie.objects.all()
    # count all objects in Movie model
    count = len(movies)
    # context of render function for show data in template of view (for path movie/list)
    context = {
        'movie_list': movies,
        'movie_count': count
    }
    return render(request, 'ticketing/movielsit.html', context)
    # return response for request with template file and data(with template : movielist.html)

    # response_text = '\n'.join('{} : {}'.format(i, movie) for i, movie in enumerate(movies, start=1))
    # return HttpResponse(str(response_text))


# view of url cinema/list with name cinema_list
def cinema_list(request):
    # query for return all objects in Cinema model
    cinemas = Cinema.objects.all()
    # count all objects in Movie model
    count = len(cinemas)
    # context of render function for show data in template of view (for path cinema/list)
    context = dict(cinema_list=cinemas, cinema_count=count)
    # return response for request with template file and data(with template : cinemalist.html)
    return render(request, "ticketing/cinemalist.html", context)


def movie_details(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    context = {
        'movie': movie
    }
    return render(request, 'ticketing/movie_details.html', context)


def cinema_details(request, cinema_id):
    cinemas = get_object_or_404(Cinema, pk=cinema_id)
    context = {
        'cinema': cinemas
    }
    return render(request, 'ticketing/cinema_details.html', context)


def showtime_list(request):
    showtime = ShowTime.objects.all()
    context = {
        "showtimes": showtime
    }
    return render(request, "ticketing/showtime_list.html", context)
    # response_text = """
    # <!DOCTYPE html>
    # <html lang="en">
    # <head>
    #     <meta charset="UTF-8">
    #     <meta name="viewport" content="width=device-width, initial-scale=1.0">
    #     <title>سینما ها</title>
    # </head>
    # <body>
    #
    #     <h1>سینما های کشور</h1>
    #     <ul>
    #         {}
    #     </ul>
    #
    # </body>
    # </html>
    # """.format('\n'.join('<li>{}</li>'.format(cinema) for cinema in cinemas))
    # return HttpResponse(response_text)

py/Django-app/Cinema/ticketing/templates/ticketing/_ad.html
 <div class="alert alert-{{ color }}">محل تبلیغات {{ company }}</div>

py/Django-app/Cinema/ticketing/templates/ticketing/base_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/bootstrap.rtl.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/bootstrap-grid.rtl.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/fontawesome.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/all.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "ticketing/css/main.css" %}">
</head>
<body style="direction: rtl;!important">
    <body dir="rtl">
    <div class="container" id="countainer">
        <div class="row align-items-center" id="header">
            <div class="col text-center">
                <h2>سامانه فروش بلیط سینما</h2>
            </div>
        </div>
        <div class="row align-items-center" id="toolbar">
            <div class="col-6 ">
                <h4>
                    {% block toolbar_title %}

                    {% endblock %}
                </h4>
            </div>
            <div class="col-6 text-left">
               {% block toolbar_button %}
                    <a class="button-fix btn btn-light py-1 px-2" href="{% url 'ticketing_app:movie_list' %}">
                          <i class="fa fa-film" aria-hidden="true"></i>
                             فیلم ها
                    </a>
                    <a class="button-fix btn btn-light py-1 px-2" href="{% url 'ticketing_app:cinema_list' %}">
                          <i class="fa fa-building" aria-hidden="true"></i>
                          سینما ها
                    </a>
               {% endblock %}
            </div>
        </div>
        {% include "ticketing/_ad.html" with company="intel" color="success"%}
        {% block main_content %}
        {% endblock %}
        {% include "ticketing/_ad.html" with company="intel" color="success"%}
    </div>



    <script src="{% static "ticketing/js/jquery-3.5.1.min.js" %}"></script>
    <script src="{% static "ticketing/js/bootstrap.js" %}"></script>
    <script src="{% static "ticketing/js/fontawesome.js" %}"></script>
    <script src="{% static "ticketing/js/main.js" %}"></script>
</body>
</html>

py/Django-app/Cinema/ticketing/templates/ticketing/cinema_details.html
{% extends 'ticketing/base_page.html' %}
   {% block title %}
        {{ cinema.name }}
   {% endblock %}

    {% block toolbar_title %}
        {{ cinema.name }}
    {% endblock %}

    {% block toolbar_button %}
        <a class="button-fix btn btn-light py-1 px-2" href="{% url 'ticketing_app:movie_list' %}">
                   <i class="fa fa-building" aria-hidden="true"></i>
                    فیلم ها
        </a>
    {% endblock %}

    {% block main_content %}
        <div class="row">
            <div class="col py-3">
                <p>شهر :
                    {{ cinema.city }}
                 </p>
                <p> ظرفیت سینما : {{ cinema.capacity }}</p>
                <p>کد سینما : {{ cinema.cinema_code }}</p>
                {% if cinema.poster %}
                    <img src="{{ cinema.poster.url }}" alt="{{cinema.name}}"
                {% else %}
                    <p style="color: red;">عکسی از سینما موجود نیست</p>
                {% endif %}
            </div>
        </div>
    {% endblock %}

py/Django-app/Cinema/ticketing/templates/ticketing/cinemalist.html
{% extends "ticketing/base_page.html" %}
{% block title %}
لیست سینما ها
{% endblock %}
{% block toolbar_title %}
فهرست سینما ها
{% endblock %}

        {% block main_content %}
        <div class="row">
            <div class="col py-3">
                {% if cinema_list %}
                    <p class=" alert-fix alert alert-success ">تعداد {{ cinema_count }} سینما موجود است.</p>
                    <ul class="list-group" id="list-show">
                        {% for cinema in cinema_list %}
                            <a href="{% url "ticketing_app:cinema_details" cinema_id=cinema.pk %}">
                                <li class="list-group-item list-group-item-action list-group-item-dark" >
                                     <i class="fa fa-building" aria-hidden="true"></i>
                                    {{ cinema }}
                                    <small class="text-muted">({{ cinema.city }})</small>
                                </li>
                            </a>
                        {% endfor %}
                    </ul>
                {% else%}
                     <p class="alert alert-danger">سینمایی وجود ندارد</p>
                {% endif %}
            </div>
        </div>
        {% endblock %}

py/Django-app/Cinema/ticketing/templates/ticketing/movie_details.html
{% extends 'ticketing/base_page.html' %}
   {% block title %}
        {{ movie.name }}
   {% endblock %}

    {% block toolbar_title %}
        {{ movie.name }}
    {% endblock %}

    {% block toolbar_button %}
        {{ block.super }}
       <a class="button-fix btn btn-light py-1 px-2" href="{% url 'ticketing_app:cinema_list' %}">
           <i class="fa fa-building" aria-hidden="true"></i>
           سینما ها
       </a>
    {% endblock %}

    {% block main_content %}
         <div class="row">
            <div class="col py-3">
                <p>کارگردان :
                    {{ movie.director }}
                 </p>
                <p>سال ساخت : {{ movie.year }}</p>
                <p>زمان فیلم : {{ movie.length }}</p>
                <p>توضیحات : {{ movie.description }}</p>
                <img src="{{ movie.poster.url}}" alt="{{ movie.name }}">
            </div>
        </div>
    {% endblock %}

py/Django-app/Cinema/ticketing/templates/ticketing/movielsit.html
{% extends "ticketing/base_page.html" %}
    {% block title %}
    فیلم  ها
    {% endblock %}
    {% block toolbar_title%}
        فهرست فیلم ها
    {% endblock %}
    {% block main_content %}
        <div class="row">
            <div class="col py-3">

                {% if movie_list %}
                    <p class="alert-fix alert alert-success ">تعداد {{ movie_count }} فیلم موجود است.</p>
                    <ul class="list-group" id="list-show">
                        {% for movie in movie_list %}
                           <a href="{% url "ticketing_app:movie_datails" movie_id=movie.pk %}">
                                 <li class="list-group-item list-group-item-action list-group-item-dark">
                                     <i class="fa fa-film" aria-hidden="true"></i>
                                    {{ movie }}
                                    <small class="text-muted">
                                        ({{ movie.director }})
                                    </small>
                                </li>
                           </a>
                        {% endfor %}
                    </ul>
                {% else%}
                     <div class="alert alert-danger">فیلمی وجود ندارد</div>
                {% endif %}
            </div>
        </div>
    {% endblock %}

py/Django-app/Cinema/ticketing/templates/ticketing/showtime_list.html
{% extends 'ticketing/base_page.html' %}
   {% block title %}
        سانس های نمایش
   {% endblock %}

    {% block toolbar_title %}
        فهرست سانس های نمایش
    {% endblock %}

    {% block main_content %}
        <div class="row">
        {% if showtimes %}
            <div class="row px-2">
                {% for showtime in showtimes %}
                    <div class="col-3 px-2 py-2">
                        <a href="#"  class="showtime-box btn
                           {% if showtime.status != showtime.SALE_OPEN %}
                                disabled btn-outline-secondary
                           {% else %}
                                btn-outline-dark
                           {% endif %}
">
                            <span>{{ showtime.movie}}</span>
                            <br>
                            <span>{{ showtime.cinema}}</span>
                            <br>
                            <span>
                                {{ showtime.start_time|date:"1 n/j ساعت H:i"}}
                            </span>
                            <span class="showtime-status badge
                                {% if showtime.status == showtime.SALE_NOT_STARTED %}
                                    badge-warning
                                {% elif showtime.status == showtime.SHOW_CANSELED %}
                                    badge-danger
                                {% elif showtime.status == showtime.SALE_OPEN %}
                                    badge-success
                                {% else %}
                                    badge-secondary
                                {% endif %}
                                ">
                                {% if showtime.status == showtime.SALE_OPEN %}
                                    {{ showtime.get_price_display }}
                                {% else %}
                                    {{ showtime.get_status_display }}
                                {% endif %}
                            </span>
                            {% if showtime.status == showtime.SALE_OPEN and showtime.free_seats < 10 %}
                                <span class="badge badge-danger">
                                    {{ showtime.free_seats }}
                                    صندلی
                                </span>
                            {% endif %}
                        </a>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <div class="alert alert-danger">
                در حال حاضر هیچ سانسی برای نمایش وجود ندارد.
            </div>
        {% endif %}
        </div>
    {% endblock %}